=== learnityframework/learnity/learnitycoreadmin/WebContent/xsd/application_template.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://learnityframework.org/"
	elementFormDefault="qualified" xmlns="http://learnityframework.org/"
	xmlns:mstns="http://learnityframework.org/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:simpleType name="NONEMPTY">
		<xsd:restriction base="xsd:token">
			<xsd:minLength value="1" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:element name="application-template">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="application-defaults" maxOccurs="1"
					minOccurs="0">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="configuration-section" maxOccurs="1"
								minOccurs="0">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="attribute" maxOccurs="unbounded"
											minOccurs="1">
											<xsd:complexType>
												<xsd:attribute name="name" use="required">
													<xsd:simpleType>
														<xsd:restriction base="xsd:string">
															<xsd:enumeration value="ThemeID" />
															<xsd:enumeration value="Enable_Caching" />
															<xsd:enumeration value="CacheName" />
															<xsd:enumeration value="CacheDynamicJS" />
															<xsd:enumeration value="CacheDynamicCSS" />
															<xsd:enumeration value="CacheDynamicImage" />
															<xsd:enumeration value="createsession" />
															<xsd:enumeration value="checkrole" />
														</xsd:restriction>
													</xsd:simpleType>
												</xsd:attribute>
												<xsd:attribute type="NONEMPTY" name="defaultvalue"
													use="required" />
											</xsd:complexType>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>

							<xsd:element name="class" maxOccurs="unbounded"
								minOccurs="0">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="section" maxOccurs="unbounded"
											minOccurs="1">
											<xsd:complexType>
												<xsd:sequence>
													<xsd:element name="attribute" maxOccurs="unbounded"
														minOccurs="1">
														<xsd:complexType>
															<xsd:attribute type="xsd:string" name="name"
																use="required" />
															<xsd:attribute type="xsd:string" name="defaultvalue"
																use="required" />
														</xsd:complexType>
													</xsd:element>
												</xsd:sequence>
												<xsd:attribute name="name" use="required">
													<xsd:simpleType>
														<xsd:restriction base="xsd:string">
															<xsd:enumeration value="structure" />
														</xsd:restriction>
													</xsd:simpleType>
												</xsd:attribute>
											</xsd:complexType>
										</xsd:element>
									</xsd:sequence>
									<xsd:attribute name="name" use="required">
										<xsd:simpleType>
											<xsd:restriction base="xsd:string">
												<xsd:enumeration value="label" />
												<xsd:enumeration value="image" />
												<xsd:enumeration value="textlink" />
												<xsd:enumeration value="list" />
												<xsd:enumeration value="listitem" />
												<xsd:enumeration value="inputtext" />
												<xsd:enumeration value="textarea" />
												<xsd:enumeration value="combo" />
												<xsd:enumeration value="button" />
												<xsd:enumeration value="form" />
												<xsd:enumeration value="iframe" />
												<xsd:enumeration value="ajaxcomponent" />
												<xsd:enumeration value="applet" />
												<xsd:enumeration value="DBgrid" />
												<xsd:enumeration value="Conditionalgrid" />
												<xsd:enumeration value="tree" />
												<xsd:enumeration value="statictree" />
												<xsd:enumeration value="dynamictree" />
												<xsd:enumeration value="dbform" />
												<xsd:enumeration value="reportwindow" />
												<xsd:enumeration value="report" />
												<xsd:enumeration value="chart" />
												<xsd:enumeration value="flashcomponent" />
												<xsd:enumeration value="inputfile" />
												<xsd:enumeration value="imagelink" />
												<xsd:enumeration value="hidden" />
												<xsd:enumeration value="checkbox" />
												<xsd:enumeration value="tab" />
												<xsd:enumeration value="password" />
												<xsd:enumeration value="radio" />
												<xsd:enumeration value="table" />
												<xsd:enumeration value="tablecell" />
												<xsd:enumeration value="tablerow" />
												<xsd:enumeration value="formdate" />
											</xsd:restriction>
										</xsd:simpleType>
									</xsd:attribute>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="framework-asset-delivery" maxOccurs="1"
					minOccurs="0">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="asset" maxOccurs="unbounded"
								minOccurs="1">
								<xsd:complexType>
									<xsd:attribute name="type" use="required">
										<xsd:simpleType>
											<xsd:restriction base="xsd:string">
												<xsd:enumeration value="js" />
												<xsd:enumeration value="css" />
											</xsd:restriction>
										</xsd:simpleType>
									</xsd:attribute>
									<xsd:attribute name="deliverymode" use="required">
										<xsd:simpleType>
											<xsd:restriction base="xsd:string">
												<xsd:enumeration value="URIPath" />
												<xsd:enumeration value="Inline" />
												<xsd:enumeration value="Dynamic" />
											</xsd:restriction>
										</xsd:simpleType>
									</xsd:attribute>

									<xsd:attribute name="pagelocation" use="required">
										<xsd:simpleType>
											<xsd:restriction base="xsd:string">
												<xsd:enumeration value="BOB" />
												<xsd:enumeration value="EOB" />
												<xsd:enumeration value="BOH" />
												<xsd:enumeration value="EOH" />
											</xsd:restriction>
										</xsd:simpleType>
									</xsd:attribute>
									<xsd:attribute type="xsd:int" name="deliverysequence"
										use="required" />
									<xsd:attribute type="xsd:string" name="filename"
										use="required" />
									<xsd:attribute type="xsd:string" name="assetpath"
										use="required" />

								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
			<xsd:attribute type="xsd:string" name="title" use="required" />
			<xsd:attribute name="UIframework" use="optional">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="bootstrap" />
						<xsd:enumeration value="jQueryUI" />
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
			<xsd:attribute type="xsd:int" name="BlockUItimeout" use="optional" />

		</xsd:complexType>

	</xsd:element>
</xsd:schema>

=== learnityframework/learnity/learnitycoreadmin/WebContent/templatexml/bootstrap-template.xml
<application-template xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://learnityframework.org/"
	xsi:schemaLocation="http://learnityframework.org/ http://localhost:8080/learnitymsme/xsd/application_template.xsd"
	title="Bootstrap" UIframework="bootstrap" BlockUItimeout="1000"> 
	<application-defaults>
		<configuration-section>
			<attribute name="ThemeID" defaultvalue="bootstrap_theme"></attribute>
			<attribute name="createsession" defaultvalue="false"></attribute>
			<attribute name="checkrole" defaultvalue="true"></attribute>
		</configuration-section>
		<class name="inputtext">
			<section name="structure">
				<attribute name="size" defaultvalue="20"></attribute>
			</section>
		</class>
		<class name="DBgrid">
			<section name="structure">
				<attribute name="CustomEditButton" defaultvalue="false"></attribute>
				<attribute name="resetSearchOnClose" defaultvalue="false"></attribute>
				<attribute name="width" defaultvalue="735"></attribute>
				<attribute name="height" defaultvalue="250"></attribute>
			</section>
		</class>
		<class name="Conditionalgrid">
			<section name="structure">
				<attribute name="CustomEditButton" defaultvalue="false"></attribute>
				<attribute name="resetSearchOnClose" defaultvalue="false"></attribute>
			</section>
		</class>
	</application-defaults>

	<framework-asset-delivery>
		<asset type="js" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="1" filename="jquery-2.2.0.js" assetpath="../coreadmin/resource/jQuery/" />
		<asset type="js" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="2" filename="grid.locale-en.js" assetpath="../coreadmin/resource/jQgrid/i18n/" />
		<asset type="js" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="3" filename="jquery.jqGrid.min.js" assetpath="../coreadmin/resource/jQgrid/" />
		<asset type="js" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="4" filename="jquery-ui.js" assetpath="../coreadmin/resource/jquery-ui/" />


		<asset type="css" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="5" filename="jquery-ui.css" assetpath="../coreadmin/resource/jquery-ui/" />
		<asset type="css" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="6" filename="jquery-ui.structure.css" assetpath="../coreadmin/resource/jquery-ui/" />
		<asset type="css" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="7" filename="jquery-ui.theme.css" assetpath="../coreadmin/resource/jquery-ui/" />

		<asset type="js" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="8" filename="engine.js" assetpath="../dwr/" />
		<asset type="js" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="9" filename="util.js" assetpath="../dwr/" />
		<asset type="js" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="10" filename="PortalEngine.js" assetpath="../dwr/interface/" />
		<asset type="js" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="11" filename="LearnityUtil.js" assetpath="../coreadmin/js/" />

		<asset type="css" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="12" filename="main2.css" assetpath="../coreadmin/css/" />

		<asset type="js" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="13" filename="jquery.validate.js" assetpath="../coreadmin/resource/validate/" />
		<asset type="js" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="14" filename="jquery.blockUI.js" assetpath="../coreadmin/resource/block/" />
		<asset type="js" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="15" filename="jquery.alphanumeric.js" assetpath="../coreadmin/js/" />

		<!-- <asset type="css" deliverymode="URIPath" pagelocation="BOH" deliverysequence="16" 
			filename="ui.jqgrid.css" assetpath="../coreadmin/resource/jQgrid/" /> -->

		<asset type="css" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="16" filename="bootstrap.css" assetpath="../coreadmin/resource/bootstrap/css/" />

		<asset type="css" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="17" filename="bootstrap-theme.css" assetpath="../coreadmin/resource/bootstrap/css/" />



		<asset type="css" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="18" filename="ui.multiselect.css" assetpath="../coreadmin/themes/" />
		<asset type="css" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="19" filename="main.css" assetpath="../coreadmin/css/" />
		<asset type="css" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="20" filename="learnity1_main.css" assetpath="../coreadmin/css/" />

		<asset type="js" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="21" filename="bootstrap.js" assetpath="../coreadmin/resource/bootstrap/js/" />

		<!-- <asset type="js" deliverymode="URIPath" pagelocation="BOH" deliverysequence="22" 
			filename="npm.js" assetpath="../coreadmin/resource/bootstrap/js/" /> -->

		<asset type="css" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="23" filename="ui.jqgrid-bootstrap.css" assetpath="../coreadmin/resource/jQgrid/" />
		<asset type="css" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="24" filename="ui.jqgrid-bootstrap-ui.css"
			assetpath="../coreadmin/resource/jQgrid/" />

		<asset type="css" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="25" filename="ui.custom-bootstrap-ui.css"
			assetpath="../coreadmin/resource/app/" />

		<asset type="js" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="26" filename="jquery.dynatree.js" assetpath="../coreadmin/resource/dynatree/" />

		<asset type="css" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="27" filename="ui.dynatree.css"
			assetpath="../coreadmin/resource/dynatree/skin-vista/" />


	</framework-asset-delivery>
</application-template>

=== learnityframework/learnity/learnitycoreadmin/WebContent/templatexml/grid_tree-template-new.xml
<application-template xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://learnityframework.org/"
	xsi:schemaLocation="http://learnityframework.org/ http://localhost:8080/learnitymsme/xsd/application_template.xsd"
	title="GridTreeNew" UIframework="jQueryUI" BlockUItimeout="500">

	<application-defaults>
		<configuration-section>
			<attribute name="ThemeID" defaultvalue="learnity"></attribute>
		</configuration-section>
		<class name="inputtext">
			<section name="structure">
				<attribute name="size" defaultvalue="20"></attribute>
			</section>
		</class>
		<class name="DBgrid">
			<section name="structure">
				<attribute name="CustomEditButton" defaultvalue="false"></attribute>
			</section>
		</class>
	</application-defaults>

	<framework-asset-delivery>
		<asset type="js" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="1" filename="jquery-2.2.0.js" assetpath="../coreadmin/resource/jQuery/" />

		<asset type="js" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="2" filename="grid.locale-en.js" assetpath="../coreadmin/resource/jQgrid/i18n/" />
		<asset type="js" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="3" filename="jquery.jqGrid.min.js" assetpath="../coreadmin/resource/jQgrid/" />
		<asset type="js" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="4" filename="jquery-ui.js" assetpath="../coreadmin/resource/jquery-ui/" />

		<asset type="css" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="5" filename="jquery-ui.css" assetpath="../coreadmin/resource/jquery-ui/" />
		<asset type="css" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="6" filename="jquery-ui.structure.css" assetpath="../coreadmin/resource/jquery-ui/" />
		<asset type="css" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="7" filename="jquery-ui.theme.css" assetpath="../coreadmin/resource/jquery-ui/" />


		<asset type="js" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="8" filename="jquery.dynatree.js" assetpath="../coreadmin/resource/dynatree/" />



		<asset type="js" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="9" filename="engine.js" assetpath="../dwr/" />
		<asset type="js" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="10" filename="util.js" assetpath="../dwr/" />
		<asset type="js" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="11" filename="PortalEngine.js" assetpath="../dwr/interface/" />
		<asset type="js" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="12" filename="LearnityUtil.js" assetpath="../coreadmin/js/" />



		<asset type="js" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="13" filename="jquery.validate.js" assetpath="../coreadmin/resource/validate/" />
		<asset type="js" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="14" filename="jquery.blockUI.js" assetpath="../coreadmin/resource/block/" />
		<asset type="js" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="15" filename="jquery.alphanumeric.js" assetpath="../coreadmin/js/" />

		<asset type="css" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="16" filename="ui.jqgrid.css" assetpath="../coreadmin/resource/jQgrid/" />

		<asset type="css" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="17" filename="ui.multiselect.css" assetpath="../coreadmin/themes/" />
		<asset type="css" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="18" filename="main.css" assetpath="../coreadmin/css/" />
		<asset type="css" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="19" filename="learnity1_main.css" assetpath="../coreadmin/css/" />

		<asset type="css" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="20" filename="ui.dynatree.css"
			assetpath="../coreadmin/resource/dynatree/skin-vista/" />
		<asset type="css" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="21" filename="main2.css" assetpath="../coreadmin/css/" />


		<asset type="css" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="22" filename="ui.multiselect.css"
			assetpath="../coreadmin/resource/jQgrid_plugins/" />


		<asset type="js" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="23" filename="jquery.contextmenu.js"
			assetpath="../coreadmin/resource/jQgrid_plugins/" />
		<asset type="js" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="34" filename="jquery.tablednd.js"
			assetpath="../coreadmin/resource/jQgrid_plugins/" />
		<asset type="js" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="35" filename="ui.multiselect.js"
			assetpath="../coreadmin/resource/jQgrid_plugins/" />

		<asset type="css" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="26" filename="ui.custom-jQgrid-ui.css" assetpath="../coreadmin/resource/app/" />

	</framework-asset-delivery>
</application-template>

=== learnityframework/learnity/learnitycoreadmin/WebContent/templatexml/grid_tree-template.xml
<application-template xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://learnityframework.org/"
	xsi:schemaLocation="http://learnityframework.org/ http://localhost:8080/learnitymsme/xsd/application_template.xsd"
	title="GridTree">
	<application-defaults>
		<configuration-section>
			<attribute name="ThemeID" defaultvalue="learnity"></attribute>
		</configuration-section>
		<class name="inputtext">
			<section name="structure">
				<attribute name="size" defaultvalue="20"></attribute>
			</section>
		</class>
		<class name="DBgrid">
			<section name="structure">
				<attribute name="CustomEditButton" defaultvalue="false"></attribute>
			</section>
		</class>
	</application-defaults>

	<framework-asset-delivery>
		<asset type="js" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="1" filename="jquery.js" assetpath="../coreadmin/js/js/" />
		<asset type="js" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="2" filename="grid.locale-en.js" assetpath="../coreadmin/js/js/i18n/" />
		<asset type="js" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="3" filename="jquery.jqGrid.min.js" assetpath="../coreadmin/js/js/" />
		<asset type="js" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="5" filename="ui.core.js" assetpath="../coreadmin/js/jquery/" />
		<asset type="js" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="6" filename="jquery.dynatree.js" assetpath="../coreadmin/js/jquery/" />
		<asset type="css" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="7" filename="ui.datepicker.css" assetpath="../coreadmin/themes/" />
		<asset type="css" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="8" filename="ui.dynatree.css" assetpath="../coreadmin/js/jquery/skin/" />
		<asset type="js" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="9" filename="engine.js" assetpath="../dwr/" />
		<asset type="js" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="10" filename="util.js" assetpath="../dwr/" />
		<asset type="js" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="11" filename="PortalEngine.js" assetpath="../dwr/interface/" />
		<asset type="js" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="12" filename="LearnityUtil.js" assetpath="../coreadmin/js/" />
		<asset type="css" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="13" filename="themes1.css" assetpath="../coreadmin/css/" />
		<asset type="css" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="14" filename="main2.css" assetpath="../coreadmin/css/" />

		<asset type="css" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="15" filename="jquery-ui-1.7.2.custom.css"
			assetpath="../coreadmin/themes/smoothness/" />
		<asset type="js" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="16" filename="jquery.validate.js" assetpath="../coreadmin/js/" />
		<asset type="js" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="17" filename="ui.datepicker.js" assetpath="../coreadmin/js/" />
		<asset type="js" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="18" filename="jquery.blockUI.js" assetpath="../coreadmin/js/" />
		<asset type="js" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="19" filename="jquery.alphanumeric.js" assetpath="../coreadmin/js/" />
		<asset type="css" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="20" filename="ui.jqgrid.css" assetpath="../coreadmin/themes/" />
		<asset type="css" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="21" filename="ui.multiselect.css" assetpath="../coreadmin/themes/" />
		<asset type="css" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="22" filename="main.css" assetpath="../coreadmin/css/" />
		<asset type="css" deliverymode="URIPath" pagelocation="BOH"
			deliverysequence="23" filename="learnity1_main.css" assetpath="../coreadmin/css/" />

	</framework-asset-delivery>
</application-template>
